### PR TITLE
WIP: feature/react-helmet

### PR DESCRIPTION
**Pull request by khenriksson**
Added react-helmet to event sites, however, I don't know if it matters in which order the tags come as they were originally quite high up but react-helmet moves them lower down. @Earlo could maybe give an input on this.

This is not yet fixed for projects to make them shareable due to running into problems with "project" being undefined.

Next step could be letting organizations add Twitter handles as well.

### CODE REVIEW

**Comment by khenriksson** [comment]
Also, we should change the production env description to make it more easily found on "hackathon platform" or similar.

**Comment by pholm** [comment]
Just checked and the meta tags are the "default ones". Also, prerender.io has to be added to make this usable for the search engines etc.

**Comment by pholm** [comment]
Seems legit for event pages now, but should be included in all views that don't require signing in: for example, project gallery, hackerpack etc. 

For non-public pages, we can use some "Log in to view this page on Junction App" SEO preview or similar.

**Comment by pholm** [comment]
@Earlo could you take a look at this? This could boost the applications significantly

**Pull request merged**
